[tools]
"aqua:github/git-sizer" = "latest"
"aqua:tstack/lnav" = "latest"
"cargo:git-delta" = "latest"
"cargo:ouch" = "latest"
"cargo:jnsgruk/oxidizr" = "latest"
"cargo:procs" = "latest"
"cargo:uv-migrator" = "latest"
"ubi:faldor20/jj_tui" = "latest"
aqua = "latest"
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
cosign = "latest"
crystal = "latest"
difftastic = "latest"
dua = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gleam = "latest"
go = "latest"
hyperfine = "latest"
jd = "latest"
jujutsu = "latest"
julia = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
nim = "latest"
node = "lts"
odin = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
sd = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
tree-sitter = "latest"
uv = "latest"
v = "latest"
viddy = "latest"
yazi = "latest"
zig = "latest"
zigmod = "latest"
# Work only tools
"aqua:gsamokovarov/jump" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"cargo:ffs" = "latest"
"cargo:jez/as-tree" = "latest"
"cargo:rnr" = "latest"
"cargo:yshavit/mdq" = "latest"
"go:github.com/josephpaul0/tdu" = "latest"
"go:gitlab.com/lesql/lesql" = "latest"
"npm:eslint" = "latest"
"ubi:fubark/cyber" = "latest"
bun = "latest"
deno = "latest"
docuum = "latest"
hadolint = "latest"
helix = "latest"
janet = "latest"
lua = "5.1"
navi = "latest"
ollama = "latest"
php = "latest"
pnpm = "latest"
raku = "latest"
ruby = "latest"
