[tools]
"aqua:github/git-sizer" = "latest"
"aqua:tstack/lnav" = "latest"
"cargo:git-delta" = "latest"
"cargo:ouch" = "latest"
"cargo:jnsgruk/oxidizr" = "latest"
"cargo:procs" = "latest"
"cargo:uv-migrator" = "latest"
"npm:backlog.md" = "latest"
"npm:@dataramen/cli" = "latest"
"npm:gren-lang" = "latest"
"npm:opencode-ai" = "latest"
"ubi:faldor20/jj_tui" = "latest"
"ubi:railwayapp/railpack" = "latest"
aqua = "latest"
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
cosign = "latest"
crystal = "latest"
difftastic = "latest"
dua = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gleam = "latest"
go = "latest"
hyperfine = "latest"
jd = "latest"
jujutsu = "latest"
julia = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
markdownlint-cli2 = "latest"
neovim = "latest"
nim = "latest"
node = "lts"
odin = "latest"
pixi = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
sd = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
tree-sitter = "latest"
uv = "latest"
v = "latest"
viddy = "latest"
yazi = "latest"
zig = "latest"
zigmod = "latest"
# Home only tools
"cargo:airshipper" = "latest"
"cargo:evcxr_repl" = "latest"
"cargo:rustlings" = "latest"
glow = "latest"
hexyl = "latest"
zls = "latest"
